version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: testquiz-mongodb
    ports:
      - "27011:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=testquiz
    restart: unless-stopped

volumes:
  mongodb_data:
